# Generated by Django 2.2.7 on 2019-11-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leche',
            old_name='Lote',
            new_name='LoteProducto',
        ),
    ]
